name: action-push
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    defaults:
      run:
        # TODO
        working-directory: ./models/iris
    steps:
      - uses: actions/checkout@v2
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '12'
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.x'
      - uses: iterative/setup-cml@v1
      - name: Train model
        run: |
          pip uninstall protobuf python3-protobuf
          pip install --upgrade pip
          pip install --upgrade protobuf

          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.PAT }}
        run: |
          python evaluate.py

          echo "## Model Metrics (json)" >> report.md
          cat score.json >> report.md
          
          cml-send-comment report.md