name: action-push
on: 
  push: 
    branches-ignore:
      - main
    paths:
      - 'models/**/**.py'
  pull_request:
    branches-ignore: 
      - main
    paths:
      - 'models/**/**.py'

jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    defaults:
      run:
        # TODO
        working-directory: ./models/iris
    steps:
      - uses: actions/checkout@v2
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '12'
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.x'
      - uses: iterative/setup-cml@v1
      - name: Pip requirement
        run: |
          pip uninstall protobuf python3-protobuf
          pip install --upgrade pip
          pip install --upgrade protobuf

          pip install -r requirements.txt
      # - name: Train model
      #   run: |
      #     # Your ML workflow goes here
      #     python train.py
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.ACC_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SEC_ID }}
        run: |
          # dvc pull
          dvc repro

          python evaluate.py

          echo "## Model Metrics" >> report.md
          dvc metrics diff HEAD --show-md >> report.md

          echo "## Data" >> report.md
          cml-publish cnf_matrix.png --md >> report.md
          
          cml-send-comment report.md